// ── SITON ENGLISH DICTIONARY (generated) ────────────────────────────
//
// The English surface of the SAME product. A key absent here falls back to
// Hebrew at runtime and is reported — it is never silently passed off as a
// translation (see `fallbackTranslationKeys`).
//
// GENERATED by `scripts/i18n/build_dictionaries.cjs` — do not hand-edit.
// Edit `scripts/i18n/en.json` and re-run it.

export const EN: Record<string, string> = {

};
