import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const workflow = await readFile(".github/workflows/stripe-sandbox-proof.yml", "utf8");
const harness = await readFile("external-tests/stripe_sandbox_authorization_release.ts", "utf8");
const packageJson = JSON.parse(await readFile("package.json", "utf8"));

assert.match(workflow, /workflow_dispatch:/);
assert.doesNotMatch(workflow, /pull_request:|\n\s*push:/, "external money-provider proof must never run for PRs or ordinary pushes");
assert.match(workflow, /environment:\s*stripe-sandbox/);
assert.match(workflow, /secrets\.STRIPE_SANDBOX_SECRET_KEY/);
assert.match(workflow, /secrets\.STRIPE_SANDBOX_PUBLISHABLE_KEY/);
assert.match(workflow, /secrets\.STRIPE_SANDBOX_WEBHOOK_SECRET/);
assert.match(workflow, /Stripe Sandbox external verification not executed/);
assert.doesNotMatch(workflow, /set\s+-x|printenv|env\s*\|/);
assert.match(harness, /startsWith\("sk_test_"\)/);
assert.match(harness, /startsWith\("pk_test_"\)/);
assert.match(harness, /startsWith\("whsec_"\)/);
assert.match(harness, /pm_card_visa/);
assert.match(harness, /pm_card_visa_chargeDeclined/);
assert.match(harness, /provider\.authorize\(input\)/);
assert.match(harness, /provider\.status\(/);
assert.match(harness, /provider\.release/);
assert.doesNotMatch(harness, /provider\.capture\s*\(/, "Stage 6b-1 must not capture");
assert.doesNotMatch(harness, /provider\.refund\s*\(/, "Stage 6b-1 must not refund");
assert.doesNotMatch(harness, /card_number|card\[number\]|\bcvv\b|\bcvc\b|exp_month|exp_year/i);
const runner = await readFile("scripts/run_stripe_sandbox_external.cjs", "utf8");
assert.match(runner, /Stripe Sandbox external verification not executed/);
assert.match(runner, /startsWith\("sk_test_"\)/);
assert.doesNotMatch(runner, /console\.(log|error)\([^\n]*(serverKey|publicKey|webhookSecret)/);
assert.equal(packageJson.scripts["test:stripe-sandbox-external"], "node scripts/run_stripe_sandbox_external.cjs");
console.log("PASS protected Stripe Sandbox external gate is manual, secret-safe, no-capture and no-refund");