#!/usr/bin/env node
/**
 * Generate `web/src/i18n/dictionaries/{he,en}.ts` from the checked-in sources:
 *
 *   scripts/i18n/seed.he.json       structurally keyed catalogues (error codes,
 *                                   CMS editor labels, state label maps)
 *   scripts/i18n/extracted.he.json  keys lifted out of the components
 *   scripts/i18n/en.json            the English dictionary
 *
 * The two .ts files are build products: never hand-edit them. `--check` fails
 * when what is on disk differs from what these sources say it should be, which
 * is what CI runs.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..");
const DICT_DIR = path.join(ROOT, "web", "src", "i18n", "dictionaries");

function readJson(file) {
  const p = path.join(ROOT, "scripts", "i18n", file);
  return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, "utf8")) : {};
}

function render(constName, title, note, entries) {
  const lines = entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  return `// ── ${title} (generated) ${"─".repeat(Math.max(0, 52 - title.length))}
//
${note.split("\n").map((l) => `// ${l}`.trimEnd()).join("\n")}
//
// GENERATED by \`scripts/i18n/build_dictionaries.cjs\` — do not hand-edit.
// Edit \`scripts/i18n/${constName === "HE" ? "seed.he.json\` / \`extracted.he.json" : "en.json"}\` and re-run it.

export const ${constName}: Record<string, string> = {
${lines.join("\n")}
};
`;
}

function build() {
  const he = { ...readJson("seed.he.json"), ...readJson("extracted.he.json") };
  const en = readJson("en.json");
  const sort = (o) => Object.entries(o).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return {
    "he.ts": render("HE", "SITON HEBREW DICTIONARY",
      "Hebrew is the canonical product language and the fallback for every key.\nKeys are hierarchical: `<surface>.<thing>` — e.g. `seller.dashboard.title`.",
      sort(he)),
    "en.ts": render("EN", "SITON ENGLISH DICTIONARY",
      "The English surface of the SAME product. A key absent here falls back to\nHebrew at runtime and is reported — it is never silently passed off as a\ntranslation (see `fallbackTranslationKeys`).",
      sort(en))
  };
}

function main() {
  const files = build();
  const check = process.argv.includes("--check");
  let bad = 0;
  for (const [name, content] of Object.entries(files)) {
    const target = path.join(DICT_DIR, name);
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
    if (check) {
      if (current !== content) { console.error(`i18n: ${name} is out of date — run scripts/i18n/build_dictionaries.cjs`); bad++; }
    } else {
      fs.writeFileSync(target, content);
    }
  }
  if (check && bad) process.exit(1);
  if (!check) {
    const he = Object.keys({ ...readJson("seed.he.json"), ...readJson("extracted.he.json") }).length;
    const en = Object.keys(readJson("en.json")).length;
    console.log(`dictionaries: he=${he} en=${en}`);
  }
}

main();
