-- RETIRED: this file intentionally contains no executable DDL.
--
-- The only database schema source of truth is the ordered manifest in
-- scripts/migration_manifest.cjs and its SQL files under src/migrations/.
-- Apply it with:
--   node scripts/run_migrations.cjs
--
-- Demo setup must use scripts/bootstrap_demo_db.cjs, which invokes that same
-- migrator before applying seed DML. Keeping this pointer prevents older
-- deployment references from silently creating a divergent schema.
