-- RETIRED historical hardening draft; intentionally contains no executable DDL.
-- Its durable schema rules are represented in the canonical SQL migration
-- chain declared by scripts/migration_manifest.cjs.
